const fs = require('fs');

const companies = [
    {
        name: "VitalSphere",
        url: "vitalsphere.html",
        goal: "Continuous health prediction AI built into wearables, homes, and clinics.",
        plan: "Ingest real-time biomarkers, sleep, and environmental data to form the core input layer of the ecosystem.",
        status: "Phase 1 (Foundation)",
        statusClass: "status-active",
        details: "VitalSphere forms the fundamental sensory input layer for BioInfinity HealthOS. By continuously pulling data from consumer wearables, at-home blood panels, and clinical electronic health records, it provides the uninterrupted data stream necessary to keep the MediTwin accurate."
    },
    {
        name: "MediTwin",
        url: "meditwin.html",
        goal: "Creates a real-time digital twin of every human body for preventive medicine.",
        plan: "Map organ-level models and simulate therapy responses to act as the central source of truth for the patient.",
        status: "Phase 1 (Foundation)",
        statusClass: "status-active",
        details: "MediTwin represents the core intelligence engine. It creates a dynamic digital replica of an individual's biology, allowing all other subsidiary AIs to run simulations, forecast aging trajectories, and model therapeutic interventions before any physical action is taken."
    },
    {
        name: "OncoMind Systems",
        url: "oncomind.html",
        goal: "Autonomous cancer detection, treatment design, and monitoring.",
        plan: "Scan for early cancer signals via liquid biopsies and simulate tumor evolution to suggest precision treatments.",
        status: "Phase 1 (Foundation)",
        statusClass: "status-active",
        details: "A dedicated oncological expert system. OncoMind analyzes imaging and circulating tumor DNA to catch cancer years before symptoms manifest. It actively interfaces with PharmaVerse to compute the optimal molecular combination to eradicate specific tumor mutations."
    },
    {
        name: "NeuroBloom AI",
        url: "neurobloom.html",
        goal: "Brain-health AI for dementia prevention, cognitive repair, and enhancement.",
        plan: "Model brain aging trajectories and recommend neurotherapeutics to preempt cognitive decline.",
        status: "Phase 1 (Foundation)",
        statusClass: "status-active",
        details: "NeuroBloom focuses on the hardest problem in longevity: preserving cognition. By analyzing neural imaging and protein biomarkers, it models individual brain-aging trajectories and suggests early neuro-protective interventions."
    },
    {
        name: "PharmaVerse AI",
        url: "pharmaverse.html",
        goal: "End-to-end AI drug discovery and simulation company.",
        plan: "Simulate billions of biological pathways to discover new protein targets and validate drugs before physical trials.",
        status: "Phase 2 (Expansion)",
        statusClass: "status-expansion",
        details: "Replacing traditional, slow drug screening with massive-scale biological simulation. PharmaVerse identifies novel protein targets and designs bespoke molecules, pushing them through 'in silico' clinical trials using populations generated by MediTwin."
    },
    {
        name: "FertiliGen",
        url: "fertiligen.html",
        goal: "AI reproductive health company optimizing fertility and embryo health.",
        plan: "Predict reproductive trajectories and safeguard maternal-fetal health using advanced predictive modeling.",
        status: "Phase 2 (Expansion)",
        statusClass: "status-expansion",
        details: "FertiliGen applies the OS's intelligence to human reproduction. It forecasts fertility windows, assesses embryo viability with supreme accuracy, and models maternal-fetal interactions to ensure optimal reproductive outcomes."
    },
    {
        name: "Longevica",
        url: "longevica.html",
        goal: "AI longevity platform that predicts, slows, and reverses aging pathways.",
        plan: "Track biological age and coordinate nutrition, regenerative therapies, and prevention plans to maximize healthspan.",
        status: "Phase 2 (Expansion)",
        statusClass: "status-expansion",
        details: "The master orchestrator. Longevica synthesizes all ecosystem data to track total biological age, optimizing sleep, nutrition, and pharmaceutical interventions to continually push back the boundaries of human healthspan."
    },
    {
        name: "GenomeForge AI",
        url: "genomeforge.html",
        goal: "AI that designs personalized gene therapies for every patient.",
        plan: "Integrate CRISPR and AI to simulate and compile custom genomic edits for rare and complex diseases.",
        status: "Phase 3 (Deep Biotech)",
        statusClass: "status-biotech",
        details: "Moving from small molecules to source code. GenomeForge architects personalized CRISPR edits and cellular therapies. It designs the genetic payload necessary to repair mutations or optimize cellular function at the fundamental level."
    },
    {
        name: "NanoCure Intelligence",
        url: "nanocure.html",
        goal: "AI-guided nanorobotic drug delivery for targeted disease treatment.",
        plan: "Determine exact tissue targeting with programmable micro-delivery to maximize payload impact and minimize side effects.",
        status: "Phase 3 (Deep Biotech)",
        statusClass: "status-biotech",
        details: "The precision delivery engine. NanoCure ensures that therapies designed by GenomeForge and PharmaVerse reach their exact cellular targets, bypassing healthy tissue and drastically reducing the systemic side effects of treatment."
    },
    {
        name: "AutoSurg Robotics",
        url: "autosurg.html",
        goal: "Fully autonomous surgical robotics with AI precision.",
        plan: "Execute AI-guided micro-scale physical interventions and precise tumor removals based on MediTwin planning.",
        status: "Phase 4 (Robotics)",
        statusClass: "status-robotics",
        details: "The physical action layer. When biological and chemical interventions are not enough, AutoSurg performs micro-scale, AI-navigated surgeries. Every procedure is planned on the patient's MediTwin before a single incision is made."
    }
];

const template = (company) => `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${company.name} | BioInfinity HealthOS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&family=Outfit:wght@400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
    <style>
        .company-hero {
            padding: 100px 20px 40px;
            max-width: 800px;
            margin: 0 auto;
            text-align: center;
        }
        .company-hero h1 {
            font-size: 4rem;
            margin-bottom: 20px;
            background: linear-gradient(to right, #fff, var(--accent));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        .back-link {
            display: inline-block;
            margin-top: 40px;
            color: var(--accent);
            text-decoration: none;
            font-weight: 600;
            border: 1px solid var(--accent);
            padding: 10px 20px;
            border-radius: 30px;
            transition: all 0.3s;
        }
        .back-link:hover {
            background: var(--accent);
            color: #fff;
        }
        .content-section {
            background: var(--card-bg);
            border: 1px solid var(--card-border);
            border-radius: 24px;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto 40px;
            backdrop-filter: blur(10px);
        }
        .content-section h3 {
            color: var(--text-muted);
            font-size: 0.9rem;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
        }
        .content-section p {
            font-size: 1.15rem;
            color: #e0e0e0;
            margin-bottom: 30px;
        }
        .content-section p:last-child {
            margin-bottom: 0;
        }
    </style>
</head>
<body>
    <div class="background-glow"></div>
    <div class="background-glow secondary"></div>

    <header class="company-hero">
        <h1>${company.name}</h1>
        <span class="status-badge ${company.statusClass}">${company.status}</span>
    </header>

    <main class="container">
        <div class="content-section">
            <h3>Goal</h3>
            <p>${company.goal}</p>
            
            <h3>Plan</h3>
            <p>${company.plan}</p>
            
            <h3>Deep Dive</h3>
            <p>${company.details}</p>
        </div>
        
        <div style="text-align: center;">
            <a href="index.html" class="back-link">&larr; Back to Ecosystem</a>
        </div>
    </main>
</body>
</html>`;

companies.forEach(company => {
    fs.writeFileSync(company.url, template(company));
    console.log(`Generated ${company.url}`);
});
